const ROLES = {
  ADMIN: "ADMIN",
  UNDERWRITER: "UNDERWRITER",
  CLAIMS_ADJUSTER: "CLAIMS_ADJUSTER",
  REINSURANCE_ANALYST: "REINSURANCE_ANALYST",
};

const ROLE_PERMISSIONS = {
  ADMIN: [
    "MANAGE_USERS",
    "MANAGE_POLICIES",
    "MANAGE_CLAIMS",
    "MANAGE_TREATIES",
    "VIEW_DASHBOARD"
  ],

  UNDERWRITER: [
    "CREATE_POLICY",
    "SUBMIT_POLICY",
    "APPROVE_POLICY",
    "VIEW_POLICY"
  ],

  CLAIMS_ADJUSTER: [
    "SUBMIT_CLAIM",
    "REVIEW_CLAIM",
    "APPROVE_CLAIM",
    "SETTLE_CLAIM",
    "VIEW_CLAIM"
  ],

  REINSURANCE_ANALYST: [
    "CREATE_TREATY",
    "VIEW_TREATY",
    "ALLOCATE_RISK",
    "VIEW_ALLOCATION",
    "VIEW_EXPOSURE_DASHBOARD"
  ]
};

module.exports = { ROLES, ROLE_PERMISSIONS };